slapd:
  image: dcm4che/slapd-dcm4chee:5.2.0
  ports:
    - "389:389"
  environment:
    LDAP_BASE_DN: dc=dcm4che,dc=org
    LDAP_ORGANISATION: dcm4che.org
    LDAP_ROOTPASS: secret
    LDAP_CONFIGPASS: secret
    DEVICE_NAME: dcm4chee-arc
    AE_TITLE: DCM4CHEE
    DICOM_HOST: localhost
    DICOM_PORT: 11112
    HL7_PORT: 2575
    SYSLOG_HOST: localhost
    SYSLOG_PORT: 8514
    # STORAGE_DIR: /storage/fs1  # dicom storage dir
  volumes:
    - ./ldap:/var/lib/ldap
    - ./slapd.d:/etc/ldap/slapd.d

mariadb:
  build: ../mariadb-dockerfile
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: pacsdb
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_USER: pacsuser
    MYSQL_PASSWORD: pacspass
  volumes:
    - ./dbdata:/var/lib/mysql

dcm4chee-arc:
  build: ../dcm4chee-dockerfile
  ports:
    - "8080:8080"
    - "9990:9990"
    - "11112:11112"
    - "2575:2575"
  environment:
    DB_ENV_MARIADB_DB: pacsdb
    DB_ENV_MARIADB_USER: pacsuser
    DB_ENV_MARIADB_PASSWORD: pacspass
  links:
    - slapd:ldap
    - mariadb:db
  volumes:
    # - ./storage:/storage
    - ./wildfly:/opt/wildfly/standalone
